[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://your-server-url.example.com/:splat"
  status = 200

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
